In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [54]:
import csv

In [55]:
# %%bash
# tail -n 10000 "coinbaseUSD.csv" > "coinbaseUSD-last_10000_trades.csv"
# wc -l "coinbaseUSD.csv"
# wc -l "coinbaseUSD-last_10000_trades.csv"

In [56]:
d = {'unix_time':[],'last_price':[],'trade_volume':[],'value':[]}

with open('coinbaseUSD-last_10000_trades.csv','r') as file:
    rows = csv.reader(file)
    for row in rows:
        d['unix_time'].append(row[0])
        d['last_price'].append(row[1])
        d['trade_volume'].append(row[2])
        d['value'].append(float(row[2])*(float(row[1])))

In [36]:
df = pd.DataFrame(d)

In [43]:
df

       unix_time         last_price    trade_volume        value
0     1537242977  6245.230000000000  0.001435520000     8.965153
1     1537242979  6245.230000000000  0.003984730000    24.885555
2     1537242980  6245.230000000000  0.027271760000   170.318414
3     1537242981  6245.220000000000  0.003090000000    19.297730
4     1537242981  6245.230000000000  0.002152490000    13.442795
5     1537242982  6245.230000000000  0.122569170000   765.472658
6     1537242983  6245.230000000000  0.030643090000   191.373145
7     1537242985  6245.230000000000  0.001993160000    12.447743
8     1537242994  6245.230000000000  0.031865120000   199.005003
9     1537242995  6245.230000000000  0.031865120000   199.005003
10    1537243000  6245.220000000000  0.029603140000   184.878122
11    1537243000  6245.220000000000  0.002296860000    14.344396
12    1537243002  6245.220000000000  0.003090000000    19.297730
13    1537243003  6245.230000000000  0.015298440000    95.542276
14    1537243020  6245.230000000000  0.007808550000    48.766191
15    1537243021  6245.230000000000  0.007966280000    49.751251
16    1537243022  6245.220000000000  0.003090000000    19.297730
17    1537243027  6245.230000000000  0.002630470000    16.427890
18    1537243031  6245.230000000000  0.030643090000   191.373145
19    1537243034  6245.220000000000  0.030000000000   187.356600
20    1537243034  6245.230000000000  0.038303460000   239.213917
21    1537243041  6245.230000000000  0.016087100000   100.467640
22    1537243041  6245.230000000000  0.023747480000   148.308475
23    1537243041  6245.220000000000  0.002325030000    14.520324
24    1537243041  6245.220000000000  0.000764970000     4.777406
25    1537243042  6245.220000000000  0.008046350000    50.251226
26    1537243042  6245.230000000000  0.150148420000   937.711417
27    1537243045  6245.220000000000  0.022228910000   138.824433
28    1537243045  6245.220000000000  0.014285710000    89.217402
29    1537243045  6245.220000000000  0.037248270000   232.623641
...          ...                ...             ...          ...
9970  1537268473  6244.510000000000  0.007650100000    47.771126
9971  1537268473  6244.510000000000  0.015457960000    96.527386
9972  1537268473  6244.500000000000  0.023000000000   143.623500
9973  1537268481  6244.500000000000  0.003090000000    19.295505
9974  1537268485  6244.510000000000  0.001435690000     8.965181
9975  1537268486  6244.510000000000  0.006300000000    39.340413
9976  1537268497  6244.510000000000  0.179000000000  1117.767290
9977  1537268503  6244.500000000000  0.003090000000    19.295505
9978  1537268504  6244.510000000000  0.007650100000    47.771126
9979  1537268509  6244.500000000000  0.150000000000   936.675000
9980  1537268511  6244.510000000000  0.001593440000     9.950252
9981  1537268520  6244.510000000000  0.015457960000    96.527386
9982  1537268521  6244.510000000000  0.003746180000    23.393058
9983  1537268521  6244.500000000000  0.003090000000    19.295505
9984  1537268521  6244.500000000000  0.003700000000    23.104650
9985  1537268532  6244.510000000000  0.157004780000   980.417919
9986  1537268534  6244.510000000000  0.003500000000    21.855785
9987  1537268542  6244.500000000000  0.003090000000    19.295505
9988  1537268546  6244.510000000000  0.038919760000   243.034831
9989  1537268553  6244.500000000000  0.044037950000   274.994979
9990  1537268556  6244.510000000000  0.007650100000    47.771126
9991  1537268562  6244.500000000000  0.003090000000    19.295505
9992  1537268565  6244.510000000000  0.003746180000    23.393058
9993  1537268567  6244.500000000000  0.066438480000   414.875088
9994  1537268581  6244.500000000000  0.003090000000    19.295505
9995  1537268588  6244.510000000000  0.030646620000   191.373125
9996  1537268588  6244.500000000000  0.163520780000  1021.105511
9997  1537268589  6244.510000000000  0.164000000000  1024.099640
9998  1537268589  6244.510000000000  0.015966160000    99.700846
9999  1537268591  6244.510000000000  0.004463220000    27.870622

[10000 rows x 4 columns]

In [52]:
(df['value'].sum())/(df['trade_volume'].sum())

TypeError: ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''